// Generated by Wrangler by running `wrangler types`

interface Env {
	ACCESS_TOKENS: KVNamespace;
	X_USER_ID: '1128638197104304128';
	GEMINI_API_KEY: string;
	SUPABASE_URL: string;
	SUPABASE_KEY: string;
	X_API_KEY: string;
	X_API_KEY_SECRET: string;
	X_BEARER_TOKEN: string;
	X_ACESS_TOKEN: string;
	X_ACESS_TOKEN_SECRET: string;
	X_CLIENT_ID: string;
	X_CLIENT_SECRET: string;
	TWITTER_REDIRECT_URI: string;
}

export { Env };
